people_per_group: 4
people:
  - Ben Nagy
  - Maryana
  - Joe
  - Sam
  - Ben Dodd
  - Lewis
  - Adam
  - Rory
  - Zenon
  - Darren
  - Sanjay
  - Tim Long
  - Tom
  - Brian
  - Abhishek
  - Kate
  - Tim Savage
  - Ben Steele
  - Rob
  - Billie
  - Dan