name:                shuffle
version:             0.1.0.0
github:              "armakuni/watercooler-selection-tool"
license:             BSD3
author:              "Tom Oram"
maintainer:          "tom.oram@armakuni.com"
copyright:           "2020 Armakuni"

extra-source-files:
- README.md

description: Please see the README

dependencies:
#- name: base
#  version: ">= 4.7 && < 5"
#  mixin: hiding (Prelude)
- name: base-noprelude
  version: ">= 4.7 && < 5"
- name: random-shuffle
- name: MonadRandom
- name: relude
#  mixin: (Relude as Prelude)
- name: text


default-extensions:
- DeriveFunctor
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TypeApplications

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - exceptions
  - fmt
  - mtl

executables:
  shuffle-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shuffle

tests:
  shuffle-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shuffle
    - hspec
    - hlint
    - ormolu
    - QuickCheck
    - quickcheck-text
